# Generated by Django 4.2.1 on 2023-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Finance_Assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=10000),
        ),
    ]
